name: Pull Request and Push checklist
run-name: Testing pnpm install / check / test / build
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AUDIO_DIR: ${{ vars.AUDIO_DIR }}
      BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL }}
      BETTER_AUTH_SECRET: ${{ vars.BETTER_AUTH_SECRET }}
      CLIENT_ID_GITHUB: ${{ vars.CLIENT_ID_GITHUB }}
      CLIENT_SECRET_GITHUB: ${{ vars.CLIENT_SECRET_GITHUB }}
      DATABASE_URL: ${{ vars.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
      - run: pnpm run check
      - run: pnpm run test
      - run: pnpm run build